// <Auto-Generated/>

namespace Cuture.EntityFramework.DynamicFilter.Test.DatabaseContext;

public class User : ITenantId, IOrganizationId, ISoftDeletion
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    public ulong OrganizationId { get; set; }

    public ulong TenantId { get; set; }

    public override string ToString()
    {
        return $"{Id}【{Name}】TenantId: {TenantId} , OrganizationId: {OrganizationId} , IsDeleted: {IsDeleted}"; 
    }
}
